### ISSUE TITLE
July Meetup

### ISSUE THREAD

**Issue by markhibberd** [scalasyd/scalasyd#17]
- [ ] #7 Tony Sloane: Scala and LLVM
- [ ] #16 Tim McGilchrist: Scala's Modular Roots
- [x] #14 Filippo Vitale: Solving CSPs in Scala (with StateT and MonadPlus)

**Comment by tmcgilchrist** [comment]
Assuming this will be on Wed 8th July?

**Comment by jedws** [comment]
yes, that is correct
