### ISSUE TITLE
May Meetup

### ISSUE THREAD

**Issue by jedws** [scalasyd/scalasyd#8]
The May meetup could/should? have the following talks:
1. [ ] #10 Ashley Valent: Monads don't compose. Free ones do
2. [ ] #2 Jacob Stanley: Tail Call Optimisation on the JVM
3. [ ] #3 Alex Hennecke: Performance Numbers for Free
