### ISSUE TITLE
June Meetup

### ISSUE THREAD

**Issue by jedws** [scalasyd/scalasyd#9]
1. [x] #11 Arnold DeVos: Wrap your imperative POJOs in Functions
2. [x] #6 Karl Roberts: How I invented Lenses
3. [x] #12 sigerber: A Parsing Fancy: Parser Combinators in Scala

**Comment by markhibberd** [comment]
@inkytonik @karlroberts ^^ You ok for this month?

**Comment by inkytonik** [comment]
Actually some things have come up with a mid-June deadline, so I would prefer July if that doesn't leave an unfillable gap in June.

**Comment by markhibberd** [comment]
@inkytonik Should be fine there are a few other proposals up.

**Comment by inkytonik** [comment]
Great, thanks. Put me down for July definitely.

**Comment by markhibberd** [comment]
@jedws Everyone has confirmed. Just got to get abstracts together. Will post tomorrow.
